[package]
name = "sync-clipboard-rust"
version = "0.1.0"
authors = ["Milan Buransky <milan.buransky@ims-evolve.com>"]

[dependencies]
clipboard = {git = "https://github.com/aweinstock314/rust-clipboard"}
byteorder = "*"
